title: ACCORD
# logo: /assets/img/logo.png
description: Collaborative Research Computing for Sensitive Data
show_downloads: false
google_analytics: G-E265TY0TZZ
remote_theme: pmarsceill/just-the-docs
accord_console: https://accord.uvarc.io/


